# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  checkout_code:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/hello-api
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hello-api
  install_dep:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/hello-api
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-us-{{ checksum "~/hello-api/package.json" }}
            - v1-dependencies-us-
      - run:
          name: Install Dependencies hello-api
          command: npm install
      - save_cache:
          key: v1-dependencies-us-{{ checksum "~/hello-api/package.json" }}
          paths:
            - ~/hello-api/node_modules
  test:
    docker:
      - image: cimg/node:15.1
      - image: mongo:4.1.6-xenial
    working_directory: ~/hello-api
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-us-{{ checksum "~/hello-api/package.json" }}
      - run:
          name: Test hello-api
          command: npm run test
  deploytodocker:
    working_directory: ~/hello-api
    docker:
      - image: cimg/node:15.1
    steps:
      - setup_remote_docker
      - run:
          name: Build & Push Docker image
          command: |
            set +x
            docker build -t quay.io/$DOCKER_LOGIN/hello-api:latest .
            echo $DOCKER_PWD | docker login quay.io -u $DOCKER_LOGIN --password-stdin
            docker push quay.io/$DOCKER_LOGIN/hello-api:latest

workflows:
  hello-api-ci:
    jobs:
      - checkout_code
      - install_dep:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
            - install_dep
      - deploytodocker:
          requires:
            - test
